Repository jenkinsci/docker-agent, pull requests merged in 2019-09, with the labels that each got.

#77 Add the Release Drafter configuration to automate changelogs
  .github/release-drafter.yml
Labels: chore

#74 Update Remoting from 3.29 to 3.35
  Dockerfile
Labels: enhancement

#54 [JENKINS-42846] - Rename slave.jar to agent.jar, keep symbolic link for compatibility
  Dockerfile
  README.md
Labels: enhancement

#80 Remove the confusing OpenJDK 8 reference from the README
  README.md
Labels: documentation

#78 Introduce release notes for the image
  README.md
Labels: documentation

#79 Reference the Jenkins Docker Gitter chat from the documentation
  README.md
Labels: documentation

#81 [JENKINS-42846] - Fix the agent.jar symbolic link in the JDK 8 image
  Dockerfile
Labels: bug

#89 Amend Java 11 documentation to reflect the GA status of Java 11 in Jenkins
  README.md
Labels: documentation
