Repository jenkinsci/docker-agent, pull requests merged in 2021-09, with the labels that each got.

#191 Correct locale
  11/alpine/Dockerfile
  11/bullseye/Dockerfile
  8/bullseye/Dockerfile
  tests/test_helpers.bash
  tests/tests.bats
Labels: bug

#192 Add s390x for debian on java 11
  Jenkinsfile
  docker-bake.hcl
Labels: enhancement

#196 Update windows images to eclipse temurin
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  8/windows/windowsservercore-ltsc2019/Dockerfile
Labels: enhancement

#197 Less prune - it can take forever
  Jenkinsfile
Labels: chore

#193 Use alpine's JRE instead of AdoptOpenJDK
  11/alpine/Dockerfile
  8/alpine/Dockerfile
  README.md
  tests/tests.bats
Labels: enhancement

#199 Remove user agent hack
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  8/windows/windowsservercore-ltsc2019/Dockerfile
Labels: chore

#200 Add metadata labels
  11/alpine/Dockerfile
  11/archlinux/Dockerfile
  11/bullseye/Dockerfile
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  8/alpine/Dockerfile
  8/bullseye/Dockerfile
  8/windows/windowsservercore-ltsc2019/Dockerfile
  docker-bake.hcl
  tests/agent.Tests.ps1
  tests/test_helpers.bash
  tests/tests.bats
Labels: enhancement
