Repository jenkinsci/docker-agent, pull requests merged in 2022-11, with the labels that each got.

#310 Fix ARM64 Java in JDK17 Bullseye
  17/bullseye/Dockerfile
  docker-bake.hcl
Labels: bug

#311 chore: ensure that JAVA_VERSION is always specified through a Docker build argument
  11/archlinux/Dockerfile
  11/bullseye/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  17/bullseye/Dockerfile
  17/windows/windowsservercore-ltsc2019/Dockerfile
Labels: chore

#312 chore: track JDK versions (11 and 17) with updatecli
  .github/dependabot.yml
  .github/workflows/updatecli.yaml
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
  updatecli/values.github-action.yaml
Labels: chore

#318 chore(updatecli) track version of remoting
  updatecli/updatecli.d/remoting.yaml
Labels: chore

#317 chore(linux tests) remove deprecated jdk17-only check
  tests/tests.bats
Labels: chore

#321 feat(linux) add curl
  11/alpine/Dockerfile
  11/archlinux/Dockerfile
  11/bullseye/Dockerfile
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  tests/tests.bats
Labels: enhancement

#326 fix(debian) Add missing packages to allow git cloning by ssh
  11/archlinux/Dockerfile
  11/bullseye/Dockerfile
  17/bullseye/Dockerfile
  tests/tests.bats
Labels: bug

#324 fix(debian_jdk17) revert #310 and use `TARGETPLATFORM` to detect if arm/v7 or not
  17/bullseye/Dockerfile
  LICENSE
  docker-bake.hcl
Labels: bug

#327 chore(updatecli) adapt manifest for v0.38.0
  .github/workflows/updatecli.yaml
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: chore

#332 chore(github-actions) cleanup workflows to only have 1 release-drafter generation
  .github/release-drafter.yml
  .github/workflows/changelog.yml
  .github/workflows/release-drafter.yml
Labels: chore

#335 chore(updatecli) tracks bats version
  Makefile
  updatecli/updatecli.d/bats.yaml
Labels: chore, tests, bats

#337 feat(linux) Add `tzdata` package
  11/alpine/Dockerfile
  11/archlinux/Dockerfile
  11/bullseye/Dockerfile
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  tests/tests.bats
Labels: enhancement

#338 feat(documentation) Adds a small paragraph describing how to use another timezone
  README.md
Labels: documentation
