Repository jenkinsci/docker-agent, pull requests merged in 2022-08, with the labels that each got.

#267 Use Alpine 3.16 instead of Alpine 3.15
  README.md
  docker-bake.hcl
Labels: dependencies

#270 Use latest Eclipse Temurin JDK releases
  .github/dependabot.yml
  11/alpine/Dockerfile
  11/bullseye/Dockerfile
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  17/windows/nanoserver-1809/Dockerfile
  17/windows/windowsservercore-ltsc2019/Dockerfile
  8/alpine/Dockerfile
  8/bullseye/Dockerfile
Labels: dependencies

#273 Use JDK 17.0.4.1 instead of JDK 17.0.4
  17/alpine/Dockerfile
  17/bullseye/Dockerfile
  17/windows/nanoserver-1809/Dockerfile
  17/windows/windowsservercore-ltsc2019/Dockerfile
Labels: bug

#275 Remove "-preview" from Java 17 images
  README.md
  docker-bake.hcl
Labels: enhancement

#274 Use JDK 11.0.16.1 instead of JDK 11.0.16
  11/alpine/Dockerfile
  11/bullseye/Dockerfile
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
Labels: bug
