Repository jenkinsci/docker-agent, pull requests merged in 2023-10, with the labels that each got.

#512 [Alpine JDK21] Bump Use Alpine to `3.18.4`
  alpine/21/Dockerfile
  updatecli/updatecli.d/alpine.yaml
Labels: chore

#516 fix(debian): replace `bullseye` by `bookworm` in tags
  docker-bake.hcl
Labels: bug

#517 Replace bullseye with bookworm in docs
  README.md
Labels: documentation

#518 feat(Windows): add Java 21
  build-windows.yaml
Labels: enhancement, windows, jdk21

#522 fix: republish a last `bullseye` set of images
  debian/fix-latest-bullseye/Dockerfile
  docker-bake.hcl
Labels: bug, jdk17, debian-linux, jdk11

#523 Revert "fix: republish a last `bullseye` set of images"
  debian/fix-latest-bullseye/Dockerfile
  docker-bake.hcl
Labels: skip-changelog

#525 chore: increase build timeout from 30 to 60 minutes
  Jenkinsfile
Labels: chore, skip-changelog

#520 breaking: set Java 17 as default
  README.md
  build.ps1
  docker-bake.hcl
Labels: enhancement, breaking, jdk17

#528 Fix issue #527: Remove removal of man-pages and documentation files.
  debian/21/Dockerfile
  debian/Dockerfile
Labels: bug, hacktoberfest, hacktoberfest-accepted, debian-linux

#530 chore: print the docker-bake targets for linux
  build.sh
Labels: enhancement, chore, skip-changelog, linux

#532 cleanup: remove "windows" group from docker-bake.hcl
  docker-bake.hcl
Labels: chore, skip-changelog, linux

#534 Upgrade Remoting from 3176.v207ec082a_8c0 to 3180.v3dd999d24861
  alpine/Dockerfile
  archlinux/Dockerfile
  build.ps1
  build.sh
  debian/Dockerfile
  docker-bake.hcl
  env.props
  tests/agent.Tests.ps1
  tests/tests.bats
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: dependencies

#521 feat(Linux): switch supported architectures to GA Temurin jdk21 images
  alpine/21/Dockerfile
  debian/Dockerfile
  debian/preview/Dockerfile
  docker-bake.hcl
Labels: enhancement, alpine-linux, jdk21, debian-linux

#535 chore(updatecli) remove reference to a deleted file for Alpine
  updatecli/updatecli.d/alpine.yaml
Labels: chore, alpine-linux, updatecli

#538 fix(jdk21-preview): correct `JAVA_MAJOR_VERSION` extraction for the EA release link
  debian/preview/Dockerfile
Labels: bug, debian-linux, jdk21-preview

#545 chore(Windows): add `-DryRun` option to build.ps1 script
  build.ps1
Labels: chore, windows

#554 chore: Bump the Jenkins remoting version to `3190.va_7870fc137d9`
  alpine/Dockerfile
  archlinux/Dockerfile
  build.ps1
  build.sh
  debian/Dockerfile
  docker-bake.hcl
  env.props
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: dependencies

#547 fix(Windows): remove duplication in tags
  build.ps1
Labels: bug, windows
