Repository jenkinsci/docker-agent, pull requests merged in 2023-05, with the labels that each got.

#416 Label Alpine container with correct version number
  docker-bake.hcl
Labels: bug

#414 chore(windows) rely on docker-compose for test phase
  build-windows.yaml
  build.ps1
  tests/agent.Tests.ps1
Labels: chore

#409 chore: factorize JDK specification to docker bakefile (linux) / compose file (windows)
  11/alpine/Dockerfile
  11/windows/nanoserver-1809/Dockerfile
  11/windows/windowsservercore-ltsc2019/Dockerfile
  17/bullseye/Dockerfile
  alpine/Dockerfile
  archlinux/Dockerfile
  build-windows.yaml
  debian/Dockerfile
  docker-bake.hcl
  windows/nanoserver-1809/Dockerfile
  windows/windowsservercore-ltsc2019/Dockerfile
Labels: chore

#419 add ksalerno99 as code owner for the debian Dockerfile
  .github/CODEOWNERS
Labels: chore

#417 chore(updatecli) fix JDK version tracking - fixup of #409
  docker-bake.hcl
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: chore

#420 chore: fix Dockerfile location on the last items - fixup of #409
  .github/dependabot.yml
  updatecli/updatecli.d/git-windows.yml
  updatecli/updatecli.d/remoting.yaml
Labels: chore

#425 hotfix(windows) use proper tagging destination to fix publication
  build.ps1
Labels: chore, windows

#423 chore(windows) cleanup tooling and nanoserver-1809 `Dockerfile`
  tests/agent.Tests.ps1
  windows/nanoserver-1809/Dockerfile
Labels: chore

#421 fix(alpine) The Alpine Dockerfile does not use the `ALPINE_TAG` arg
  alpine/Dockerfile
Labels: bug, alpine-linux

#426 chore(alpine): Uses `updatecli` to stay up to date
  updatecli/updatecli.d/alpine.yaml
Labels: chore

#428 Cleanup: correct unused code
  alpine/Dockerfile
  build.ps1
Labels: chore
