Repository jenkinsci/docker-agent, pull requests merged in 2023-07, with the labels that each got.

#442 feat: use a multi-stage image for Windows Server Core
  windows/windowsservercore-ltsc2019/Dockerfile
Labels: enhancement, windows

#444 cleanup(updatecli): deduplicate manifest targets
  updatecli/updatecli.d/git-windows.yaml
  updatecli/updatecli.d/remoting.yaml
Labels: chore

#450 chore(build): remove unnecessary `timestamps()` call
  Jenkinsfile
Labels: skip-changelog

#445 refactor(build): factorize Jenkinsfile steps
  Jenkinsfile
  build-windows.yaml
  build.ps1
  tests/test_helpers.psm1
  updatecli/updatecli.d/git-windows.yaml
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
  updatecli/updatecli.d/remoting.yaml
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: chore

#452 chore(updatecli) fixups of JDK manifests and remove depreciation warnings
  .github/workflows/updatecli.yaml
  build-windows.yaml
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: chore, updatecli

#454 chore(dependabot): new folders since refactoring
  .github/dependabot.yml
Labels: chore

#460 chore(test): correct `CONTAINERNAME`
  tests/agent.Tests.ps1
Labels: skip-changelog

#458 chore(tests) fixup build to pass Windows version image tag as build arg for Pester docker tests
  build.ps1
  tests/agent.Tests.ps1
  tests/test_helpers.psm1
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: chore

#441 feat: add Windows Server and Nanoserver LTSC 2022 images
  Jenkinsfile
  README.md
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
Labels: enhancement

#461 chore(build): output in logs the list of Windows images and tags to be processed
  build.ps1
Labels: chore
