Repository jenkinsci/docker-agent, pull requests merged in 2024-08, with the labels that each got.

#853 Set remoting version to `3206.3208.v409508a_675ff`
  alpine/Dockerfile
  archlinux/Dockerfile
  build.ps1
  build.sh
  debian/Dockerfile
  docker-bake.hcl
  env.props
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: enhancement, agent

#857 Bugfix: Fix regression where environment variables set to USER would be lowercased to user.
  alpine/Dockerfile
  archlinux/Dockerfile
  debian/Dockerfile
  tests/tests_agent.bats
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: bug

#860 Add support for Jenkins agent jar file location in the environment variable JENKINS_AGENT_FILE
  README_inbound-agent.md
  jenkins-agent
Labels: enhancement, documentation, inbound-agent
