Repository jenkinsci/docker-agent, pull requests merged in 2024-09, with the labels that each got.

#868 chore(temurin Adoptium install scripts) provide visibility for `curl` and retry downloads
  adoptium-get-jdk-link.sh
  adoptium-install-jdk.sh
Labels: chore, adoptium-scripts

#827 chore: align with docker-ssh-agent build process
  .gitignore
  Jenkinsfile
  Makefile
  README.md
  build-windows.yaml
  build.ps1
  docker-bake.hcl
  env.props
  tests/agent.Tests.ps1
  tests/inbound-agent.Tests.ps1
  tests/test_helpers.psm1
  updatecli/updatecli.d/jdk11.yaml
  updatecli/updatecli.d/jdk17.yaml
  updatecli/updatecli.d/jdk21.yaml
  updatecli/updatecli.d/remoting.yaml
  windows/windowsservercore/Dockerfile
Labels: enhancement, chore, documentation

#880 chore: follow-up of UBI9 image introduction
  README.md
  docker-bake.hcl
Labels: chore, rhel-ubi9

#881 chore(Jenkinsfile) fix `withEnv` syntax error
  Jenkinsfile
Labels: skip-changelog

#884 chore(Jenkinsfile): set `ON_TAG` to `true` to publish tagged versions of the images
  Jenkinsfile
Labels: chore
