Repository jenkinsci/docker-agent, pull requests merged in 2024-07, with the labels that each got.

#831 Fix Debian-based Docker image `org.opencontainers.image.source` label
  debian/Dockerfile
Labels: bug

#833 Revert "hotfix(Windows Server Core LTSC2019) pin 2019 images to April version"
  build-windows.yaml
  build.ps1
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: chore, windows

#844 chore(Jenkinsfile) increase DockerHub rate limit with authentication
  Jenkinsfile
Labels: skip-changelog
