Repository jenkinsci/docker-agent, pull requests merged in 2024-01, with the labels that each got.

#570 feat: build both agent and inbound agent
  .github/workflows/update-dockerhub-description.yaml
  .gitignore
  Jenkinsfile
  Makefile
  README.md
  README_agent.md
  README_inbound-agent.md
  alpine/Dockerfile
  build.ps1
  build.sh
  debian/Dockerfile
  debian/preview/Dockerfile
  docker-bake.hcl
  jenkins-agent
  jenkins-agent.ps1
  tests/agent.Tests.ps1
  tests/inbound-agent.Tests.ps1
  tests/netcat-helper/Dockerfile
  tests/netcat-helper/Dockerfile-windows
  tests/test_helpers.bash
  tests/test_helpers.psm1
  tests/tests_agent.bats
  tests/tests_inbound-agent.bats
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: enhancement, windows, linux, agent, inbound-agent

#582 chore(doc): small cleanup
  README.md
  README_inbound-agent.md
Labels: chore, documentation

#746 Update Java versions and Debian version
  debian/Dockerfile
  debian/preview/Dockerfile
  docker-bake.hcl
Labels: chore

#747 chore: fix repository references
  README_agent.md
  README_inbound-agent.md
  windows/nanoserver/Dockerfile
  windows/windowsservercore/Dockerfile
Labels: chore
