Repository jenkinsci/docker-agent, pull requests merged in 2025-10, with the labels that each got.

#1060 Use Trixie in the Debian container name, not Bookworm
  README_agent.md
  docker-bake.hcl
Labels: bug

#1066 chore(linux): no dot in jlink version switch
  alpine/Dockerfile
  debian/Dockerfile
  rhel/ubi9/Dockerfile
Labels: chore, linux

#1071 chore(pipeline): split `Build and Test` stage
  Jenkinsfile
  build.ps1
Labels: chore, skip-changelog
